import {AiFillStar} from "react-icons/ai";

const products_data = [
    {
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Nike Air Monarch IV",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "white",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        title: "Nike Air Vapormax Plus",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "red",
        category: "sneakers",
    },

    {
        img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        title: "Nike Waffle One Sneaker",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        title: "Nike Running Shoe",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        title: "Flat Slip On Pumps",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Vans",
        color: "green",
        category: "flats",
    },
    {
        img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        title: "Knit Ballet Flat",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "flats",
    },

    {
        img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        title: "Loafer Flats",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Vans",
        color: "white",
        category: "flats",
    },

    {
        img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        title: "Nike Zoom Freak",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },

    {
        img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        title: "Nike Men's Sneaker",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Adidas",
        color: "blue",
        category: "sneakers",
    },

    {
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "PUMA BLACK-OCE",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "green",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        title: "Pacer Future Sneaker",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "red",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        title: "Unisex-Adult Super",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "black",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        title: "Roma Basic Sneaker",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "white",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        title: "Pacer Future Doubleknit",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "black",
        category: "sneakers",
    },

    {
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "Fusion Evo Golf Shoe",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Puma",
        color: "green",
        category: "sneakers",
    },
    {
        img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        title: "Rainbow Chex Skate",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "red",
        category: "flats",
    },
    {
        img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        title: "Low-Top Trainers",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "white",
        category: "sandals",
    },
    {
        img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        title: "Vans Unisex Low-Top",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "blue",
        category: "sandals",
    },
    {
        img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        title: "Classic Bandana Sneakers",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Nike",
        color: "black",
        category: "sandals",
    },
    {
        img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        title: "Chunky High Heel",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Vans",
        color: "black",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        title: "Slip On Stiletto High Heel",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "puma",
        color: "black",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        title: "DREAM PAIRS Court Shoes",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Nike",
        color: "red",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        title: "Nike Air Vapormax Plus",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "red",
        category: "sneakers",
    },

    {
        img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        title: "Low Mid Block Heels",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "black",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
        title: "Chunky High Heel",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        title: "Amore Fashion Stilettos",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Adidas",
        color: "white",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        title: "Bridal Sandals Glitter",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "heels",
    },
    {
        img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        title: "Wedding Prom Bridal",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "flats",
    },
    {
        img: "https://www.prestige.co.uk/cdn/shop/products/76709.jpg?v=1599816239",
        title: "Stainless Steel Cookware Set",
        star: <AiFillStar className="rating-star" />,
        reviews: "(32 reviews)",
        prevPrice: "$120.00",
        newPrice: "95",
        company: "Kitchen Pro",
        color: "silver",
        category: "kitchen",
    },
    {
        img: "https://m.media-amazon.com/images/I/61Mnz8TFQAL.jpg",
        title: "Non-Stick Baking Pan Set",
        star: <AiFillStar className="rating-star" />,
        reviews: "(21 reviews)",
        prevPrice: "$35.00",
        newPrice: "28",
        company: "BakeMaster",
        color: "black",
        category: "kitchen",
    },
    {
        img: "https://media.4rgos.it/s/Argos/8490801_R_SET?$Main768$&w=620&h=620",
        title: "Digital Kitchen Scale",
        star: <AiFillStar className="rating-star" />,
        reviews: "(45 reviews)",
        prevPrice: "$20.00",
        newPrice: "15",
        company: "Smart Kitchen",
        color: "white",
        category: "kitchen",
    },
    {
        img: "https://www.whiteley.co.uk/wp-content/uploads/2021/10/leather-knife-roll-19.jpg",
        title: "Chef's Knife Set",
        star: <AiFillStar className="rating-star" />,
        reviews: "(37 reviews)",
        prevPrice: "$50.00",
        newPrice: "40",
        company: "Culinary Essentials",
        color: "wood",
        category: "kitchen",
    },

    // Electronics Category (4 products)
    {
        img: "https://i.ebayimg.com/thumbs/images/g/l4sAAOSw20RhWUZQ/s-l500.jpg",
        title: "Smart LED TV",
        star: <AiFillStar className="rating-star" />,
        reviews: "(65 reviews)",
        prevPrice: "$500.00",
        newPrice: "450",
        company: "Tech Innovators",
        color: "black",
        category: "electronics",
    },
    {
        img: "https://static.wixstatic.com/media/04997e_68e5af5940ef44bd95956c05f01a9938~mv2.jpg/v1/fill/w_850,h_850,al_c,q_85,enc_auto/04997e_68e5af5940ef44bd95956c05f01a9938~mv2.jpg",
        title: "Wireless Bluetooth Earbuds",
        star: <AiFillStar className="rating-star" />,
        reviews: "(42 reviews)",
        prevPrice: "$80.00",
        newPrice: "65",
        company: "SoundWave",
        color: "white",
        category: "electronics",
    },
    {
        img: "https://media.currys.biz/i/currysprod/10230024?$l-large$&fmt=auto",
        title: "Portable Power Bank",
        star: <AiFillStar className="rating-star" />,
        reviews: "(28 reviews)",
        prevPrice: "$30.00",
        newPrice: "22",
        company: "ChargeMate",
        color: "blue",
        category: "electronics",
    },
    {
        img: "https://hips.hearstapps.com/hmg-prod/images/best-wifi-security-cameras-1676897187.jpg?crop=1.00xw:1.00xh;0,0&resize=1200:*",
        title: "Smart Home Security Camera",
        star: <AiFillStar className="rating-star" />,
        reviews: "(36 reviews)",
        prevPrice: "$70.00",
        newPrice: "55",
        company: "SecureTech",
        color: "silver",
        category: "electronics",
    },

    // Cleaning Essentials Category (5 products)
    {
        img: "https://www.maxima-clean.co.uk/wp-content/uploads/2018/03/max20034-all-purpose-cleaner-spray.jpg",
        title: "All-Purpose Cleaner Spray",
        star: <AiFillStar className="rating-star" />,
        reviews: "(18 reviews)",
        prevPrice: "$8.00",
        newPrice: "6",
        company: "CleanMaster",
        color: "green",
        category: "cleaning essentials",
    },
    {
        img: "https://m.media-amazon.com/images/I/81GwKOPUXsL._AC_UF894,1000_QL80_.jpg",
        title: "Microfiber Cleaning Cloths",
        star: <AiFillStar className="rating-star" />,
        reviews: "(25 reviews)",
        prevPrice: "$12.00",
        newPrice: "9",
        company: "UltraClean",
        color: "yellow",
        category: "cleaning essentials",
    },
    {
        img: "https://m.media-amazon.com/images/I/61ZpCztYTCS.jpg",
        title: "Robot Vacuum Cleaner",
        star: <AiFillStar className="rating-star" />,
        reviews: "(34 reviews)",
        prevPrice: "$150.00",
        newPrice: "120",
        company: "AutoSweep",
        color: "black",
        category: "cleaning essentials",
    },
    {
        img: "https://m.media-amazon.com/images/I/61qYE76D1nL._AC_UF894,1000_QL80_.jpg",
        title: "Bamboo Fiber Dishcloths",
        star: <AiFillStar className="rating-star" />,
        reviews: "(14 reviews)",
        prevPrice: "$6.00",
        newPrice: "4",
        company: "EcoClean",
        color: "natural",
        category: "cleaning essentials",
    },
    {
        img: "https://m.media-amazon.com/images/I/615t9M+7IPL.jpg",
        title: "Reusable Cleaning Wipes",
        star: <AiFillStar className="rating-star" />,
        reviews: "(22 reviews)",
        prevPrice: "$10.00",
        newPrice: "7",
        company: "GreenWipe",
        color: "blue",
        category: "cleaning essentials",
    },

    // Toiletries Category (6 products)
    {
        img: "https://m.media-amazon.com/images/I/71VFtEWAYOL._AC_UF894,1000_QL80_.jpg",
        title: "Luxury Bamboo Bath Towel Set",
        star: <AiFillStar className="rating-star" />,
        reviews: "(48 reviews)",
        prevPrice: "$40.00",
        newPrice: "30",
        company: "PureComfort",
        color: "white",
        category: "toiletries",
    },
    {
        img: "https://m.media-amazon.com/images/I/612lRG+6mTL.jpg",
        title: "Organic Lavender Shampoo",
        star: <AiFillStar className="rating-star" />,
        reviews: "(33 reviews)",
        prevPrice: "$15.00",
        newPrice: "12",
        company: "NatureCare",
        color: "purple",
        category: "toiletries",
    },
    {
        img: "https://digitalcontent.api.tesco.com/v2/media/ghs/51f05bea-da68-4f93-8c65-1a9f7c433bb8/f58de78d-2a4c-4435-857e-7dd3d051047b_1266777616.jpeg?h=960&w=960",
        title: "Men's Grooming Kit",
        star: <AiFillStar className="rating-star" />,
        reviews: "(29 reviews)",
        prevPrice: "$28.00",
        newPrice: "20",
        company: "GentlemanStyle",
        color: "black",
        category: "toiletries",
    },
    {
        img: "https://m.media-amazon.com/images/I/812EP8qwNpL._AC_UF1000,1000_QL80_.jpg",
        title: "Scented Bath Bombs Set",
        star: <AiFillStar className="rating-star" />,
        reviews: "(26 reviews)",
        prevPrice: "$18.00",
        newPrice: "15",
        company: "FizzBliss",
        color: "assorted",
        category: "toiletries",
    },
    {
        img: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1640187741-luxury-hand-wash-diptyque-1640187717.jpg?crop=0.639xw:0.788xh;0.175xw,0.103xh&resize=980:*",
        title: "Luxury Hand Soap Dispenser",
        star: <AiFillStar className="rating-star" />,
        reviews: "(38 reviews)",
        prevPrice: "$12.00",
        newPrice: "9",
        company: "SoftTouch",
        color: "silver",
        category: "toiletries",
    },
    {
        img: "https://cdn.thewirecutter.com/wp-content/media/2022/10/essential-oil-diffuser-2048px-4274.jpg",
        title: "Essential Oil Diffuser",
        star: <AiFillStar className="rating-star" />,
        reviews: "(44 reviews)",
        prevPrice: "$25.00",
        newPrice: "20",
        company: "AromaZen",
        color: "wood",
        category: "toiletries",
    },
];

export default products_data;